/* eslint-disable jsx-a11y/alt-text */
/* eslint-disable react/no-unescaped-entities */
import Head from 'next/head';
import Image from 'next/image';
import formImage from '../public/form.jpg'
import { useFormik } from 'formik';
import * as Yup from 'yup'
import {useRouter } from 'next/router';
import {motion as m} from 'framer-motion';

// 39.22

export default function Home() {

  // router
  const router = useRouter();


  // formik logics
  const formik = useFormik({
    initialValues: {
      name: "",
      email: "",
      country: "United Kingdom",
      terms: "",
    },// Validate form
    validationSchema: Yup.object({
      name: Yup.string().max(20, 'Name must be 20 charracters or less').required('Name is required'),
      email: Yup.string().email('Invalid email address').required('Email is required'),
      terms: Yup.array().required('Terms of services must be checked')
    }),

    validationSchema: Yup.object({
      name: Yup.string()
        .max(20, "Name must be 20 characters or less.")
        .required("Name is required"),
      email: Yup.string()
        .email("Invalid email address")
        .required("Email is required"),
      terms: Yup.array().required("Terms of service must be checked"),
    }),

    onSubmit: (values) => {
      console.log("form submitted");
      router.push({pathname: '/success', query: values})
      
    },


  })

  console.log(formik.errors)

  return (

    <m.div initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} className='abs'>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/public/favicon.ico' />
      </Head>

      <main className=' h-1/6 mt-1 flex items-center justify-center'>
        <form onSubmit={formik.handleSubmit}
          className="bg-white flex rounded-lg w-4/5 font-latoRegular">
          <div className='flex-1 text-gray-700 p-5'>
            <h1 className='text-3xl pb-2 font-latoBold'>Let's get started 👋</h1>
            <p className='text-lg text-gray-500'>Join our E-learning platform today and unlock over 500+ courses
              and digital assets ready to download.</p>

            <div className='mt-6'>
              {/* name input */}
              <div className='pb-4'>
                <label className={`block font-latoBold text-sm pb-2 ${formik.touched.name && formik.errors.name ? 'text-red-400' : ''}`} htmlFor="name">
                  {formik.touched.name && formik.errors.name ? formik.errors.name : 'Name'}
                </label>
                <input className='border-2 border-gray-500 p-2 rounded-md w-1/2 focus:border-teal-500 focus:ring-teal-500'
                  type="text"
                  name='name'
                  placeholder='Enter your name'
                  value={formik.values.name}
                  onChange={formik.handleChange}
                  onBlur={formik.handleBlur}
                />
              </div>

              {/* eamil input */}
              <div className='pb-4'>
                <label className={`block font-latoBold text-sm pb-2 ${formik.touched.email && formik.errors.email ? 'text-red-400' : ''}`} htmlFor="email"> {formik.touched.email && formik.errors.email ? formik.errors.email : 'Email'} </label>
                <input className='border-2 border-gray-500 p-2 rounded-md w-1/2 focus:border-teal-500 focus:ring-teal-500'
                  type="email"
                  name='email'
                  placeholder='Enter your email'
                  value={formik.values.email}
                  onChange={formik.handleChange}
                  onBlur={formik.handleBlur}
                />
              </div>

              {/* country input */}
              <div className='pb-4'>
                <label className='block font-latoBold text-sm pb-2' htmlFor="country">Country</label>
                <select
                  value={formik.values.country}
                  onChange={formik.handleChange}
                  name="contry"
                  className='border-2 border-gray-500 p-2 rounded-md w-1/2 focus:border-teal-500 focus:ring-teal-500'>
                  <option>United State</option>
                  <option>United Kigdom</option>
                  <option>Germany</option>
                  <option>Norway</option>
                </select>
              </div>

              {/* terms of services */}
              <div className='pb-4'>
                <label className={`block font-latoBold text-sm pb-2 ${formik.touched.terms && formik.errors.terms ? 'text-red-400' : ''}`} htmlFor="terms"> {formik.touched && formik.errors.terms ? formik.errors.terms : 'Terms of servic'} </label>
                <div className='flex items-center gap-2'>
                  <input
                    value='checked'
                    type="checkbox"
                    name='terms'
                    className='h-5 w-5 text-teal-500 border-2  background-gray-500 focus:border-teal-500 focus:ring-teal-500'
                    onChange={formik.handleChange}
                  />
                  <p className='text-sm font-latoBold text-gray-500'> I agree to the Terms and Service that my data will be taken and sold.</p>
                </div>
              </div>

              <button type='submit' className='bg-teal-500 font-latoBold text-sm text-white py-3 mt-6 rounded-lg w-full'>Start learning today!</button>
            </div>
          </div>

          <div className='relative flex-1'>
            <Image src={formImage} alt='form-learn' priority fill className='object-cover rounded-r-lg ' />
          </div>

        </form>
      </main>
    </m.div>

  );
}
